apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - llama-training-pipeline.yaml

commonLabels:
  app.kubernetes.io/managed-by: argocd
  project: keti-ai-storage
  component: pipeline
