apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - application.yaml           # 단순 워크로드 배포 (ai-workload-test)
  - pipeline-application.yaml  # Kubeflow Pipeline 배포 (kubeflow-user-example-com)
